[package]
name = "onyx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = { git = "https://github.com/nmattia/rnix-parser", rev="017baaa0076a352115ce5837c3f9c36d912a7905" }

rowan = "0.15.0"
