[package]
name = "onyx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = { git = "https://github.com/nix-community/rnix-parser" }

rowan = "0.15.0"
