name: Test code and deploy playground

on:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      # First, setup rust and test code
      - name: Checkout
        uses: actions/checkout@v3
      - run: rustup default 1.63
      - run: cargo test


      # Then, build wasm and app
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cd playground/wasm && wasm-pack build --dev
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      # We need to set the base url because the deploy target is "nmattia.github.io/onyx/"
      - run: cd playground/app && npm ci && BASE_URL="/onyx/" npm run build

      # Set everything up related to deployment
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'playground/app/dist'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v1
